DELETE FROM [dbo].[Records]
WHERE Id < 100
DBCC CHECKIDENT('Records', RESEED, 0)
DELETE FROM [dbo].[Players]
WHERE Id < 100
DBCC CHECKIDENT('Players', RESEED, 0)
DELETE FROM [dbo].[Games]
WHERE Id < 100
DBCC CHECKIDENT('Games', RESEED, 0)

